### PR TITLE
New Appearance Options

### PR DESCRIPTION
**Pull request by Caeden117**
This PR adds a new set of options to ChroMapper, aimed at tweaking the appearance of notes and the overall lighting of the editor.

New settings:

- **Note Color Multiplier:** Exposes a hidden setting in the Note shader, allowing users to darken or lighten the color of the note block.
- **Arrow Color Multiplier:** Much the same as `Note Color Multiplier`, instead applying to the note arrow.
- **Arrow Color White Blend:** Blends the color of the note arrow to a pure white.
- **Obstacle Opacity:** Adjusts opacity of the obstacles inner core.
- **Alternate Lighting:** Tweaks CM's lighting to closer match MMA2's by straightening the main directional light and adding a secondary directional light to the player.

As a bonus, you can now see the map editor while viewing the settings screen 😉 (this was a bug)

### CODE REVIEW

**Comment by XAce1337manX** [comment]
The sliders values aren't highlighted at default values.
image

I'll push a fix for that.

**Comment by XAce1337manX** [comment]
Obstacle Opacity doesn't seem to do anything.

**Comment by XAce1337manX** [comment]
Chain segments aren't affected by new appearance options:
image

**Comment by Caeden117** [comment]
image

New CM users will be able to select a lighting preset to automatically adjust these new lighting settings

**Review by XAce1337manX — APPROVED** [review]
Looks good.

**Pull request merged**
