### PR TITLE
Add song audio control

### PR DESCRIPTION
**Pull request by Top-Cat**
Add new slider to control song volume so that you can make metronome or hitsounds louder than the song.
Fix master volume not being set correctly due to audio reset.
Update translations.

### CODE REVIEW

**Review by Caeden117 — CHANGES_REQUESTED** [review]
Changing Song audio should apply at runtime while in the editor

**Comment by Top-Cat** [comment]
> Changing Song audio should apply at runtime while in the editor (EDIT: scene, not the Unity Editor)

It should already?

**Comment by Caeden117** [comment]
I understand that it updates when you first play the song, but it should probably also update *while* the song is playing

**Comment by Top-Cat** [comment]
> I understand that it updates when you ~first play~ start playing the song, but it should probably also update _while_ the song is playing

I figured people wouldn't be changing options while their song was playing and it made it 10x easier to implement. But if you want.

**Comment by Caeden117** [comment]
If not, I *guarantee* you that someone would report it as a bug. It's an odd inconsistency that the other audio settings (Master, hit sounds, metronome) update as soon as the setting is changed, but the song audio setting doesn't. Not to mention people would expect the song audio to update as soon as the setting is changed

**Comment by Top-Cat** [comment]
> If not, I _guarantee_ you that someone would report it as a bug. It's an odd inconsistency that the other audio settings (Master, hit sounds, metronome) update as soon as the setting is changed, but the song audio setting doesn't. Not to mention people would expect the song audio to update as soon as the setting is changed

Metronome actually doesn't work if starts disabled

**Comment by Caeden117** [comment]
that should probably be fixed too then, but probably not this PR

**Pull request merged**
