### PR TITLE
#fixed Dragging ring propagations #56

### PR DESCRIPTION
**Pull request by Xavjer**

### CODE REVIEW

**Comment by Xavjer** [comment]
@Caeden117 I needed to know if I am in ring propagation within the BeatmapEventContainer, so I created a method within the TracksManager for it.

I don't know the best practice to do that, maybe just a get method would have been better, if so just tell me and i'll change it accordingly

**Comment by Caeden117** [comment]
I dislike using `TracksManager` to grab Ring Propagation, since the job of `TracksManager` is completely unrelated to that. What I'd recommend is adding a `EventsContainer` parameter into `BeatmapEventContainer.SpawnEvent()`, something like this:

```cs
public static BeatmapEventContainer SpawnEvent(this EventsContainer container, MapEvent data, ...```

**Comment by Xavjer** [comment]
Ok, so I am gonna change that like you suggested this evening.

**Comment by Xavjer** [comment]
@Caeden117 Made the changes as you suggested

**Pull request merged**
