### PR TITLE
Keybind rejig + assorted other changes

### PR DESCRIPTION
**Pull request by Top-Cat**
- Moved/Added the following:
  - Precision placement toggle `Q`
  - Reset rings `Numpad 0`
  - Camera attach to note grid `Ctrl+R`
  - Leave options menu `Escape`
- Fixed rocket center prop id order
- Add chroma suggestion for environment removal, could bump this to a requirement?
- Fixed offset precision placement
- Removed waveform follows workflow option

### CODE REVIEW

**Review by Caeden117 — CHANGES_REQUESTED** [review]
Keybind proposals conflict a little bit here:
- `Ctrl+R` for camera attaching to note grid conflicts with `Ctrl+R` for precision 360/90 rotation
  - Not sure who cares about precision 360/90 rotation now, but it does still exist
- `Numpad 0` for resetting rings conflicts with `Alt + Numpad 0-9` for laser speed input
  - EDIT: While laser speed input does reply on `Alt` being held, due to the unique nature of how it's implemented, it will not block the Reset Rings action from firing

**Comment by Top-Cat** [comment]
Precision 360/90 is just R not Ctrl+R?

**Comment by Top-Cat** [comment]
And now I see that numpad conflicts for note diagonals too, hmm

**Comment by Caeden117** [comment]
I dont think anyone would miss the dedicated diagonal note keys

(and yes Precision 360/90 is `R`, my bad)

**Comment by Top-Cat** [comment]
I've added some workarounds that stop the numpad hotkeys working while laser speed editing is happening. For some reason this didn't work via disable / clearing action maps 🤷

**Review by Caeden117 — APPROVED** [review]
alright, looks good to me now

**Pull request merged**
