### PR TITLE
1.13.4 env

### PR DESCRIPTION
**Pull request by Top-Cat**
Prop reordering for new update

Still need to test some of these as KDA took way too long and I rushed through the rest

### CODE REVIEW

**Review by Caeden117 — APPROVED** [review]
LGTM, cant wait for these to be broken next update 😃

**Comment by Top-Cat** [comment]
Ready for some testing

**Comment by Top-Cat** [comment]
Now with kone

**Review by Caeden117 — APPROVED** [review]
kalcbwujavgcuscope

**Pull request merged**
