### PR TITLE
Add basic angleOffset support

### PR DESCRIPTION
**Pull request by GojiCrafter**
Adds angleOffset visualization
Loads from JSON but doesn't save to JSON; Bullet has that fixed though

### CODE REVIEW

**Comment by Caeden117** [comment]
is bullet waiting for this PR to be merged before he opens the fix? I'd rather he instead make a PR to your branch so its included in _this_ PR.

**Comment by GojiCrafter** [comment]
true true I agree with your statement, time to ping bullet repeatedly

**Comment by XAce1337manX** [comment]
I was asleep. PR'd to Goji's branch.

**Comment by GojiCrafter** [comment]
Bullet's PR merged

**Review by Caeden117 — APPROVED** [review]
LGTM

**Pull request merged**
