### PR TITLE
fix difficulty label not showing immediately on copy

### PR DESCRIPTION
**Pull request by GalaxyMaster2**
This had been bugging me for a while and it turned out to be a one line fix.

### CODE REVIEW

**Comment by Top-Cat** [comment]
I think my original assumption is that you wouldn't actually want to copy a custom diff name so I would have cleared the custom data value. (It's possible originally we didn't copy it but since adding copying for colours it's now being copied too?)

**Comment by GalaxyMaster2** [comment]
> I think my original assumption is that you wouldn't actually want to copy a custom diff name so I would have cleared the custom data value. (It's possible originally we didn't copy it but since adding copying for colours it's now being copied too?)

To me it makes sense to also copy the custom label, but I could see arguments for either way. Shouldn't be hard to just not copy the label instead, but either is preferable to the current broken behavior.

**Comment by Top-Cat** [comment]
I'd like a second opinion, I do agree the current behaviour needs changing

**Comment by GalaxyMaster2** [comment]
Seems good to me, done

**Pull request merged**
