### PR TITLE
[Dev] Light Changes

### PR DESCRIPTION
**Pull request by UrkiMimi**
Basically when messing around with the ChroMapper unity project I changed these things.

-Mirrors are reflected in Triangle and Default environments
-Lights now use unlit shaders
-Mirror material uses new textures used on the current bs mirrors

### CODE REVIEW

**Comment by Top-Cat** [comment]
This is literally a PR from branches only in our repo. Might want to try again.

**Comment by Top-Cat** [comment]
Oh, it's a zip. Please no, that's not how PRs work.

**Comment by UrkiMimi** [comment]
got it

**Comment by UrkiMimi** [comment]
I am very sorry this is my first pull request

**Comment by Top-Cat** [comment]
https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by Caeden117** [comment]
It's a complicated process for a newcomer, however it's much easier for us to integrate the changes as a proper Pull Request rather than merging file changes ourselves

**Pull request merged**
