### PR TITLE
Added Chromatoggle for Walls and Notes

### PR DESCRIPTION
**Pull request by AsoVR**
Hi, I've added ChromaToggle support for Notes and Walls
GitHub was a bit jank

Any feedback/changes are accepted 👍

### CODE REVIEW

**Comment by Top-Cat** [comment]
Ok, but why have you removed all the translations?

**Comment by AsoVR** [comment]
let me see 1 sec

**Comment by Caeden117** [comment]
Yeah, this seems like its missing some recent changes made to the `dev` branch. Can you please rebase your changes from the `dev` branch?

**Comment by AsoVR** [comment]
how can i do that?

**Comment by Caeden117** [comment]
[Might have to do some command line git magic to pull it off, but here's the docs](https://git-scm.com/book/en/v2/Git-Branching-Rebasing)

**Comment by AsoVR** [comment]
i think i might have fixed it but im not sure

**Comment by Top-Cat** [comment]
Personally I'd squash it, but the diff looks a lot smaller. Still shouldn't have `m_EditorVersion: 2019.3.0f6`

**Comment by AsoVR** [comment]
my bad, i didn't realised unity set it to open in 3.0f6 rather than 3.15f1

**Comment by AsoVR** [comment]
I think I'm gonna close the PR and try again. Most of the issues have come from me not using GitHub Desktop properly and I think I could fix some messy code and make the UI a tiny bit better, thanks for the feedback

**Pull request closed without merging**
