### PR TITLE
v4 Format Support

### PR DESCRIPTION
**Pull request by XAce1337manX**
Features:
* Can edit v4 maps - Mainly for compatibility with official editor
* Saving with incompatible data in format will prompt a warning
* Additions to Song Info screen to support new fields
  * Vanilla: 
    * Mappers, lighters, and shared lightshow fields
    * Environment selection per diff
  * Custom:
    * Read support for custom characteristics
    * Stub wip menu for new SongCore features (lets users know the feature exists)
    * Small UX improvements to pop up menus (rewording and closing)

| SongCore custom characteristic display | Environment Removal moved into Custom Properties menu |
| :-: | :-: |
| image | image |

(If any one wants to offer suggestions to the menu, feel free)

Brief overview of changes:
* BeatSaberSong replaced with BaseInfo. Reading to and writing from this is handled in V2Info and V4Info
  * A majority of changes will be just changing this reference
  * V4 classes, as with V2 and V3, just handle IO
* New maps are created with v4 info as it gives access to some new metadata fields and still supports difficulties of any version.
* New difficulties are still created in v3 as CustomJSONData does not have a specification for v4. For now, v4 custom properties will display with v3 json in editor and will not persist on save

_Lots of things to deal with. I expect to find more bugs when this gets merged._

### CODE REVIEW

**Comment by XAce1337manX** [comment]
Well. 1.40 just dropped with a bunch of map new features.

**Comment by Caeden117** [comment]
I don’t think the 1.40 additions to v4 blocks the PR. If you feel its ready for a dev merge, go for it, but I do totally understand if you want to ensure the latest features get added beforehand

**Comment by XAce1337manX** [comment]
Plans for this PR is probably:
* Merge after stable push - dev is in a stable state atm so I'm going to see if there's any bug fixes I can push to that before
* Add new fields to this PR so CM doesn't yeet them
  * No support in editor for this PR

**Comment by XAce1337manX** [comment]
Here we go.

**Pull request merged**
