### PR TITLE
Add release channel dropdown in experimental

### PR DESCRIPTION
**Pull request by Top-Cat**
Watch this space

Obviously does nothing immediately, but I think I need a "stable" build to support this setting before it makes sense to do anything else.

experimental

### CODE REVIEW

**Comment by Caeden117** [comment]
how about i accept this PR so you have to keep making new ones

haha... just kidding...

...unless?

**Comment by Top-Cat** [comment]
image

What's that up there?

**Review by Caeden117 — APPROVED** [review]
looks good to me

wait i mean "k"

**Pull request merged**
